name: Compliance Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  run-compliance-check:
    runs-on: self-hosted  # Use your local self-hosted runner
    permissions:
      actions: read  # Allow reading actions from GitHub
      contents: write  # Allow reading repository contents
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run local compliance script
        run: |
          echo "Running compliance check on self-hosted runner..."
          python "C:\Users\soumy\OneDrive\Desktop\ASU\Thesis\Basic example\compliance_check.py"

      - name: Post results
        shell: powershell
        run: |
          if (Test-Path compliance_report.json) {
              Get-Content compliance_report.json
          } else {
              Write-Output "No compliance report found"
          }

      - name: Upload compliance report
        uses: actions/upload-artifact@v4.6.1
        with:
          name: compliance-report
          path: compliance_report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
